src-git packages https://github.com/SamKnows/lede_packages.git^5910cc84659367580acaa056326f75dd3c59e47d
src-git samknows git@github.com:SamKnows/skopenwrt_packages.git^a0222becae1d07527af9d3a612aaf1af958226b3
