src-git packages https://github.com/SamKnows/lede_packages.git^1add90e7c45a73c8a4f02ced8cd8d32b60382203
src-git samknows git@github.com:SamKnows/skopenwrt_packages.git^a7ace8d3e2564735850d2508980db7b17b4666b3
